### ISSUE TITLE
List of typo's

### ISSUE THREAD

**Issue by kordejong** [ModernCPPBook/moderncppbook.github.io#1]
Dear authors,

Thank you for the Parallel C++ book. I enjoy reading it.

I think I found some typos in the book. I have not finished reading it completely, but here is the list I made so far. Page numbers are in PDF reader pages, not in book pages. I am not a native English speaker so I may be completely wrong with my suggestions.

Kind regards,
Kor

- 7: However, with the C++ 17 and C++ 20 → Remove "the"
- 7: features of the C++ 17 and C++ 20 → Remove "the"
- 7: container and algorithms → "containers"
- 16: run the examples in within → Remove "in"
- 20: compile the codeIn Line → Add ". "
- 20: is build using → "built"
- 25: the proposal recommend the → "recommends"
- 29: showed the components, we will → Remove ","
- 29: a list or any of → "of"
- 29: With the C++ standard the iterator → "C++ 20"
- 31: In Line 7 the values are read → Text is out of sync with examples
- 34: How the even/odd cases are handled in the code (lines 16-21) seem not in line with the even/odd cases in formula 3.3
- 35: an randomly chosen → "a"
- 37: The array ... are very similar → "The arrays"
- 39: by cppstd::end() → "std::end()" (markup error I guess)
- 40: Listing, line 22 → Variable "index" is not used (updated).
- 40: the variable index is incremented → Out of sync with the listing
- 47: the generate images → "generated"
- 47: the generating of the images → "generation"
- 47: amount of iterations → "number of"
- 47: MAX_ITER=- → "MAX_ITER -"
- 48: kernels.hpp → kernel.hpp
- 50: Mandelbrot ans Julia → "and"
- 53: Overheads work required → "Overheads of work"
- 55: therefore many → Remove "therefore"
- 55: Examples for this → "of this"
- 58: to the HPX → Remove "the"
- 62: due unbalanced → "due to unbalanced"
- 63: track data dependency → "a data dependency"
- 63: Footnotes → Slashes are missing
- 67: A portion ... were extended → "is extended"
- 69: library is  [80] → Remove one space
- 69: Listing, line 29 → Are a header and namespace missing? Where does the PLL `parallel_for` come from?
- 78: hope too do → "do"
- 78: cannot speed up → "cannot be sped up"
- 80: but it the → Remove "it"
- 83: Parallelism Computer Architectures → "Parallel"
- 84: is the instructions → "are"
- 88: once all  threads finished → Remove space
- 90: Figure 8.2 ... shows the performance ... → Is this the correct figure? Text and figure seem out of sync
- 93: Line 10 → "Compute" (capital)
- 94: ... vector and store ... instead → "but"
- 94: partial some → "sum"

**Comment by diehlpk** [comment]
I will fix the code after I corrected all typos. Here is the list of open issues:

- 34: How the even/odd cases are handled in the code (lines 16-21) seem not in line with the even/odd cases in formula 3.3
- 40: Listing, line 22 → Variable "index" is not used (updated).
- 40: the variable index is incremented → Out of sync with the listing

**Comment by diehlpk** [comment]
Stopped at `69: Listing, line 29 → Are a header and namespace missing? Where does the PLL parallel_for come from?` and will proceed soon.

**Comment by diehlpk** [comment]
@kordejong Thanks for the list of issues. I fixed all typos and will look into the code next week.

**Comment by diehlpk** [comment]
- 34: How the even/odd cases are handled in the code (lines 16-21) seem not in line with the even/odd cases in formula 3.3

That is correct and I updated the example and the book.

**Comment by diehlpk** [comment]
@kordejong I added your suggestions here https://hpxbook.stellar-group.org/addendum/2024/08/15/addendum.html
